### ISSUE TITLE
Insert the cursor on the first run

### ISSUE THREAD

**Issue by gusinacio** [streamingfast/substreams-sink-sql#20] opened 2023-05-23 01:03 UTC
Usually, when the sink stops is because of abnormally termination, for example OOM, killed by the Kubernetes, etc.
When this occurs, it doesn't shutdown gracefully and is terminated without the cursor write.

It has an cursor update, but the first insert of cursor is on the first termination.

**Comment by maoueh** [comment] 2023-05-25 04:11
That is the expected behavior, the postgres sink batches write to write to the database only each X blocks (1000 I think by default) and will write the cursor only if the full batch is written.

That being said, maybe there is something else you are describing and I did not get it.

**Comment by gusinacio** [comment] 2023-05-26 02:13
> and will write the cursor only if the full batch is written.

It's not been inserted in the first full batch. It's only been inserted on a graceful shutdown and after that it updates as expected.

**Comment by maoueh** [comment] 2023-05-26 20:40
Yeah I'm working on refactoring a bit the cursor handling when the module hash changes and I noticed this piece of code that write the cursor on shutdown.

This code is actually quite wrong, you want to update the cursor only after that has been correctly flushed, otherwise you will end up missing some data (because we saved a cursor while some data in memory have not been flushed!).

Luckily, this code was also bad because it does an insert so if I previous cursor already exist, it should be good. And then you are also right that the flush code does only an update, so there is stuff wrong in there also (I doubt postgres accepts that).

Anyway, it's going to be fixed early next week, I won't have time to push a new release just know (I'm done with the code, doing some testing now).

**Comment by maoueh** [comment] 2023-05-26 21:08
Oh boy, I just understand why it "pass". It's because we were not checking if at least one row was updated, so the query was actually working but affected no rows.

This is broken since I release v2 because it's me who remove the initial insert when the database was empty, damn it sorry.

**Comment by maoueh** [comment] 2023-05-26 21:27
`develop` is fixed, I'll release early next week.

**Comment by maoueh** [comment] 2023-05-29 19:40
Released in v2.2.0 with a new behavior when the `.spkg` change.

**Closed as completed by maoueh** 2023-05-29 19:40 UTC
